server:
  port: 8001
spring:
  application:
    name: user
  datasource:
    url: jdbc:oracle:thin:@172.17.0.1:49161/xe
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

